import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Localization Service for English and Tamil languages
class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  SharedPreferences? _prefs;
  String _currentLanguage = 'en';

  String get currentLanguage => _currentLanguage;
  String get currentLanguageName => _currentLanguage == 'en' ? 'English' : 'தமிழ்';

  Future<void> init() async {
    _prefs = await SharedPreferences.getInstance();
    _currentLanguage = _prefs?.getString('language') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String langCode) async {
    _currentLanguage = langCode;
    await _prefs?.setString('language', langCode);
    notifyListeners();
  }

  /// Get translated string by key with optional arguments for interpolation
  String tr(String key, {Map<String, String>? args}) {
    String text = _translations[_currentLanguage]?[key] ?? _translations['en']?[key] ?? key;
    
    if (args != null && args.isNotEmpty) {
      args.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }
    
    return text;
  }

  /// All translations
  static final Map<String, Map<String, String>> _translations = {
    'en': {
      // Common
      'app_name': 'Director Hub Pro',
      'ok': 'OK',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'close': 'Close',
      'confirm': 'Confirm',
      'yes': 'Yes',
      'no': 'No',

      // Navigation
      'directors': 'Directors',
      'reports': 'Reports',
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      'profile': 'Profile',

      // Settings Screen
      'security': 'SECURITY',
      'biometric_login': 'Biometric Login',
      'use_face_fingerprint': 'Use Face ID or Fingerprint',
      'push_notifications': 'Push Notifications',
      'receive_alerts': 'Receive alerts and updates',
      'preferences': 'PREFERENCES',
      'dark_mode': 'Dark Mode',
      'switch_dark_theme': 'Switch to dark theme',
      'language': 'Language',
      'text_display': 'TEXT DISPLAY',
      'name_case_format': 'Name Case Format',
      'choose_display': 'Choose how director names are displayed',
      'title_case': 'Title Case',
      'uppercase': 'UPPERCASE',
      'lowercase': 'lowercase',
      'data_sync': 'DATA & SYNC',
      'sync_data': 'Sync Data',
      'last_synced': 'Last synced just now',
      'syncing_data': 'Syncing data with cloud...',
      'backup': 'Backup',
      'create_backup': 'Create local backup',
      'creating_backup': 'Creating backup...',
      'activity_log': 'Activity Log',
      'view_activity': 'View recent activity',
      'loading_activity': 'Loading activity log...',
      'about': 'ABOUT',
      'about_app': 'About App',
      'version': 'Version 1.0.4',
      'help_support': 'Help & Support',
      'get_help': 'Get help using the app',
      'opening_help': 'Opening help center...',
      'logout': 'Log Out',
      'confirm_logout': 'Confirm Logout',
      'logout_message': 'Are you sure you want to log out? You will need to sign in again.',

      // Directors Screen
      'all_directors': 'All Directors',
      'records_found': 'records found',
      'search_directors': 'Search directors...',
      'add_director': 'Add Director',
      'edit_director': 'Edit Director',
      'director_details': 'Director Details',
      'name': 'Name',
      'din': 'DIN',
      'pan': 'PAN',
      'email': 'Email',
      'phone': 'Phone',
      'status': 'Status',
      'active': 'Active',
      'inactive': 'Inactive',
      'address': 'Address',
      'no_din': 'No DIN',
      'export': 'Export',
      'filter': 'Filter',
      'sort': 'Sort',
      'columns': 'Columns',
      'removed': 'Removed',
      'restore': 'Restore',
      'permanently_delete': 'Permanently Delete',

      // Reports Screen
      'create_campaign': 'Create Campaign',
      'campaign_title': 'Campaign Title',
      'selection_mode': 'SELECTION MODE',
      'single': 'Single',
      'multi': 'Multi',
      'start_campaign': 'START CAMPAIGN',
      'categories': 'Categories',
      'add_category': 'Add Category',
      'assigned': 'Assigned',
      'pending': 'Pending',
      'insights_dashboard': 'Insights Dashboard',
      'total': 'TOTAL',
      'quality_status': 'Quality Status',
      'poor': 'POOR',
      'average': 'AVERAGE',
      'excellent': 'EXCELLENT',
      'last_updated': 'Last Updated',
      'not_answered': 'Not Answered',
      'assignments': 'ASSIGNMENTS',
      'recent_surveys': 'RECENT SURVEYS',
      'efficiency': 'EFFICIENCY',
      'single_selection': 'Single Selection',
      'multi_selection': 'Multi Selection',
      'report_not_found': 'Report Not Found',
      'report_not_found_desc': 'This report could not be found.',
      'no_categories_yet': 'No categories yet',
      'add_category_start': 'Add a category to start assigning directors',
      'rename': 'Rename',
      'no_directors_in_category': 'No directors in this category',
      'add_director': 'Add Director',
      'edit_director': 'Edit Director',
      'create_new_record': 'Create a new director record',
      'update_info': 'Update director information',
      'identification': 'IDENTIFICATION',
      'full_name': 'Full Name',
      'enter_full_name': 'Enter full name',
      'din_number': 'DIN Number',
      'enter_din': 'Enter 7-8 digit DIN',
      'pan_number': 'PAN Number',
      'aadhaar_number': 'Aadhaar Number',
      'contact_info': 'CONTACT INFORMATION',
      'email_id': 'Email ID',
      'bank_linked_phone': 'Bank Linked Phone',
      'aadhaar_pan_phone': 'Aadhaar/PAN Phone',
      'email_linked_phone': 'Email Linked Phone',
      'address_info': 'ADDRESS INFORMATION',
      'aadhaar_address': 'Aadhaar Address',
      'residential_address': 'Residential Address',
      'idbi_bank_details': 'IDBI BANK DETAILS',
      'account_details': 'Account Details',
      'emudhra_details': 'eMUDHRA ACCOUNT DETAILS',
      'status_label': 'STATUS',
      'create_director': 'Create Director',
      'update_director': 'Update Director',
      'name_required': 'Name is required',
      'director_created_synced': 'Director created & synced to cloud',
      'director_updated_synced': 'Director updated & synced to cloud',
      'inactive': 'Inactive',
      'enter_phone': 'Enter phone number',
      'phone_number': 'Phone number',
      'enter_address_aadhaar': 'Enter address as per Aadhaar',
      'enter_residential_address': 'Enter current residential address',
      'enter_account_details_idbi': 'Enter account number, customer ID, etc.',
      'enter_account_details_emudhra': 'Enter A/c number, bank name, IFSC, branch',
      'removed_directors': 'Removed Directors',
      'search_removed_directors': 'Search removed directors...',
      'restore': 'Restore',
      'delete_forever': 'Delete Forever',
      'permanently_delete_title': 'Permanently Delete?',
      'permanently_delete_confirm': 'Are you sure you want to permanently delete "{name}"?',
      'undone_action_warning': 'This action cannot be undone!',
      'restore_success': '{name} has been restored',
      'delete_forever_success': '{name} has been permanently deleted',
      'no_removed_directors': 'No Removed Directors',
      'all_directors_active': 'All directors are currently active',
      'removed': 'Removed',
      'analytics_overview': 'Analytics Overview',
      'performance_monitoring': 'Performance and compliance monitoring',
      'directorship_distribution': 'Directorship Distribution',
      'active_inactive_status': 'Active vs Inactive Status',
      'data_integrity': 'Data Integrity',
      'completeness_validation': 'Completeness and validation status',
      'profile_completion': 'Profile Completion',
      'din_validation': 'DIN Validation',
      'kyc_status': 'KYC Status',
      'total_records': 'Total Records',
      'issues': 'Issues',
      'synced': 'Synced',
      'quarterly_audit_report': 'Quarterly Audit Report',
      'full_compliance_check': 'Full compliance check for all mandates',
      'export_master_report': 'Export Master Report',
      'download_success_msg': 'Master Report PDF downloaded to secure storage.',
      'opening_audit_report': 'Opening detailed audit report...',
      'export_directors': 'Export Directors',
      'directors_selected': '{count} of {total} directors selected',
      'export_format': 'Export Format',
      'document_settings': 'Document Settings',
      'report_title': 'Report Title',
      'enter_report_title': 'Enter report title',
      'company_name_optional': 'Company Name (Optional)',
      'enter_company_name': 'Enter company name',
      'file_name': 'File Name',
      'enter_file_name': 'Enter file name',
      'include_header': 'Include Header',
      'add_title_metadata': 'Add title and metadata at the top',
      'include_timestamp': 'Include Timestamp',
      'add_generation_date': 'Add generation date and time',
      'include_summary': 'Include Summary',
      'add_stats_end': 'Add statistics at the end',
      'privacy': 'Privacy',
      'aadhaar_privacy': 'Aadhaar Privacy',
      'unmasked': 'Unmasked',
      'show_full_number': 'Show full number',
      'masked': 'Masked',
      'hide_digits': 'Hide digits',
      'select_fields': 'Select Fields',
      'choose_fields_export': 'Choose which fields to include in the export',
      'exporting': 'Exporting...',
      'export_count_directors': 'Export {count} Directors',
      'select_directors_to_export': 'Select Directors to Export',
      'all_directors_selected': 'All Directors Selected',
      'tap_choose_specific': 'Tap to choose specific directors',
      'search_directors': 'Search directors...',
      'hide_selection': 'Hide Selection',
      'selected': 'Selected',
      'name_case_format': 'Name Case Format',
      'choose_case_display': 'Choose how director names are displayed',
      'title_case': 'Title Case',
      'uppercase': 'UPPERCASE',
      'lowercase': 'lowercase',
      'logout_confirm_msg': 'Are you sure you want to log out of your account?',
      'about_app_desc': 'A professional director management solution with cloud sync and real-time collaboration.',
      'close': 'Close',
      'default_language_desc': 'Default language',
      'live_synced': 'Live • Synced',
      'syncing': 'Syncing...',
      'synced_directors_msg': 'Synced {count} directors',
      'no_directors_yet': 'No directors yet',
      'start_adding_msg': 'Start by adding your first director to the database',
      'mismatch': 'Mismatch',
      's_no': 'S.No',
      'pan': 'PAN',
      'aadhaar_address': 'Aadhaar Address',
      'residential_address': 'Residential Address',
      'idbi_account': 'IDBI Account',
      'emudhra_account': 'eMudhra Account',
      'bank_phone': 'Bank Linked Phone',
      'aadhaar_phone': 'Aadhaar/PAN Phone',
      'email_phone': 'Email Linked Phone',
      'has_valid_din': 'Has Valid DIN',
      'generated_at': 'Generated',
      'summary_section': 'Summary',
      'yes': 'Yes',
      'no': 'No',

      // Login Screen
      'welcome': 'Welcome',
      'login_title': 'Director Hub',
      'secure_access_msg': 'Secure access to your director records',
      'username': 'Username',
      'password': 'Password',
      'enter_username': 'Enter your username',
      'enter_password': 'Enter your password',
      'sign_in': 'Sign In',
      'demo_credentials': 'Demo: admin / password',
      'invalid_credentials': 'Invalid credentials. Please try again.',
      'field_required': 'This field is required',

      // Dashboard
      'welcome_back': 'Welcome Back',
      'overview': 'Overview',
      'total_directors': 'Total Directors',
      'active_directors': 'Active Directors',
      'pending_issues': 'Pending Issues',
      'recent_activity': 'Recent Activity',
      'key_metrics': 'Key Metrics',
      'quick_actions': 'Quick Actions',
      'recent_directors': 'Recent Directors',
      'view_all': 'View All',
      'no_din_proposal': 'No DIN / Proposal',
      'address_mismatch': 'Address Mismatch',
      'sync': 'Sync',
      'mismatch': 'Mismatch',
      'synced_directors': 'Synced directors',
      'live_synced': 'Live • Synced',
      'syncing': 'Syncing...',

      // Profile
      'admin_user': 'Admin User',
      'administrator': 'Administrator',
      'edit_profile': 'Edit profile',

      // Misc
      'select_language': 'Select Language',
      'english': 'English',
      'tamil': 'தமிழ்',
      'home': 'Home',
      'cards': 'Cards',
      'table': 'Table',
      'cols': 'Cols',
      'add_to_category': 'Add to "{category}"',
      'directors_available_count': '{count} directors available. Tap to add.',
      'all_directors_assigned': 'All directors assigned!',
      'no_more_to_add': 'No more directors to add.',
      'added_success': 'Added {name}',
      'search_hint_name_din': 'Search by name or DIN...',
      'done': 'Done',

      // Forms
      'dynamic_forms': 'DJM Form',
      'fill_manage_forms': 'Fill or manage custom DJM forms and reports',
      'create_form': 'Create DJM Form',
      'edit_form': 'Edit DJM Form',
      'delete_form': 'Delete DJM Form',
      'form_title': 'DJM Form Title',
      'form_description': 'DJM Form Description',
      'add_field': 'Add Field',
      'save_form': 'Save DJM Form',
      'view_reports': 'View Reports',
      'responses': 'Responses',
      'export_csv': 'Export Excel (CSV)',
      'export_pdf': 'Export PDF',
      'no_forms_available': 'No DJM forms available yet',
      'submit_form': 'Submit DJM Form',
      'form_submitted_success': 'DJM Form submitted successfully!',
    },
    'ta': {
      // Common - தமிழ்
      'app_name': 'டைரக்டர் ஹப் புரோ',
      'ok': 'சரி',
      'cancel': 'ரத்து செய்',
      'save': 'சேமி',
      'delete': 'நீக்கு',
      'edit': 'திருத்து',
      'add': 'சேர்',
      'search': 'தேடு',
      'loading': 'ஏற்றுகிறது...',
      'error': 'பிழை',
      'success': 'வெற்றி',
      'close': 'மூடு',
      'confirm': 'உறுதிப்படுத்து',
      'yes': 'ஆம்',
      'no': 'இல்லை',

      // Navigation - வழிசெலுத்தல்
      'directors': 'இயக்குனர்கள்',
      'reports': 'அறிக்கைகள்',
      'dashboard': 'டாஷ்போர்டு',
      'settings': 'அமைப்புகள்',
      'profile': 'சுயவிவரம்',

      // Settings Screen - அமைப்புகள் திரை
      'security': 'பாதுகாப்பு',
      'biometric_login': 'பயோமெட்ரிக் உள்நுழைவு',
      'use_face_fingerprint': 'முக அடையாளம் அல்லது கைரேகை பயன்படுத்தவும்',
      'push_notifications': 'புஷ் அறிவிப்புகள்',
      'receive_alerts': 'விழிப்பூட்டல்கள் மற்றும் புதுப்பிப்புகளைப் பெறுங்கள்',
      'preferences': 'விருப்பங்கள்',
      'dark_mode': 'இருண்ட பயன்முறை',
      'switch_dark_theme': 'இருண்ட தீம்க்கு மாறவும்',
      'language': 'மொழி',
      'text_display': 'உரை காட்சி',
      'name_case_format': 'பெயர் வடிவம்',
      'choose_display': 'இயக்குனர் பெயர்கள் எவ்வாறு காட்டப்படும் என்பதைத் தேர்ந்தெடுக்கவும்',
      'title_case': 'தலைப்பு வழக்கு',
      'uppercase': 'பெரிய எழுத்து',
      'lowercase': 'சிறிய எழுத்து',
      'data_sync': 'தரவு & ஒத்திசைவு',
      'sync_data': 'தரவை ஒத்திசை',
      'last_synced': 'இப்போது ஒத்திசைக்கப்பட்டது',
      'syncing_data': 'கிளவுட் உடன் தரவை ஒத்திசைக்கிறது...',
      'backup': 'காப்புப்பிரதி',
      'create_backup': 'உள்ளூர் காப்புப்பிரதி உருவாக்கு',
      'creating_backup': 'காப்புப்பிரதி உருவாக்குகிறது...',
      'activity_log': 'செயல்பாட்டு பதிவு',
      'view_activity': 'சமீபத்திய செயல்பாட்டைக் காண்க',
      'loading_activity': 'செயல்பாட்டு பதிவை ஏற்றுகிறது...',
      'about': 'பற்றி',
      'about_app': 'செயலி பற்றி',
      'version': 'பதிப்பு 1.0.4',
      'help_support': 'உதவி & ஆதரவு',
      'get_help': 'செயலியைப் பயன்படுத்த உதவி பெறுங்கள்',
      'opening_help': 'உதவி மையத்தைத் திறக்கிறது...',
      'logout': 'வெளியேறு',
      'confirm_logout': 'வெளியேற்றத்தை உறுதிப்படுத்து',
      'logout_message': 'நீங்கள் வெளியேற விரும்புகிறீர்களா? மீண்டும் உள்நுழைய வேண்டும்.',

      // Directors Screen - இயக்குனர்கள் திரை
      'all_directors': 'அனைத்து இயக்குனர்கள்',
      'records_found': 'பதிவுகள் கண்டறியப்பட்டன',
      'search_directors': 'இயக்குனர்களைத் தேடு...',
      'add_director': 'இயக்குனரைச் சேர்',
      'edit_director': 'இயக்குனரைத் திருத்து',
      'director_details': 'இயக்குனர் விவரங்கள்',
      'name': 'பெயர்',
      'din': 'DIN',
      'pan': 'PAN',
      'email': 'மின்னஞ்சல்',
      'phone': 'தொலைபேசி',
      'status': 'நிலை',
      'active': 'செயலில்',
      'inactive': 'செயலற்றது',
      'address': 'முகவரி',
      'no_din': 'DIN இல்லை',
      'export': 'ஏற்றுமதி',
      'filter': 'வடிகட்டி',
      'sort': 'வரிசைப்படுத்து',
      'columns': 'நெடுவரிசைகள்',
      'removed': 'அகற்றப்பட்டது',
      'restore': 'மீட்டெடு',
      'permanently_delete': 'நிரந்தரமாக நீக்கு',

      // Reports Screen - அறிக்கைகள் திரை
      'create_campaign': 'பிரச்சாரத்தை உருவாக்கு',
      'campaign_title': 'பிரச்சார தலைப்பு',
      'selection_mode': 'தேர்வு முறை',
      'single': 'ஒற்றை',
      'multi': 'பல',
      'start_campaign': 'பிரச்சாரத்தைத் தொடங்கு',
      'categories': 'வகைகள்',
      'add_category': 'வகையைச் சேர்',
      'assigned': 'ஒதுக்கப்பட்டது',
      'pending': 'நிலுவையில்',
      'insights_dashboard': 'நுண்ணறிவு டாஷ்போர்டு',
      'total': 'மொத்தம்',
      'quality_status': 'தர நிலை',
      'poor': 'மோசம்',
      'average': 'சராசரி',
      'excellent': 'சிறந்தது',
      'last_updated': 'கடைசியாக புதுப்பிக்கப்பட்டது',
      'not_answered': 'பதிலளிக்கவில்லை',
      'assignments': 'பணிகள்',
      'recent_surveys': 'சமீபத்திய ஆய்வுகள்',
      'efficiency': 'திறன்',
      'single_selection': 'ஒற்றை தேர்வு',
      'multi_selection': 'பல தேர்வு',
      'report_not_found': 'அறிக்கை கண்டறியப்படவில்லை',
      'report_not_found_desc': 'இந்த அறிக்கையைக் கண்டறிய முடியவில்லை.',
      'no_categories_yet': 'இன்னும் பிரிவுகள் இல்லை',
      'add_category_start': 'இயக்குனர்களை ஒதுக்க ஒரு பிரிவைச் சேர்க்கவும்',
      'rename': 'பெயர் மாற்றவும்',
      'no_directors_in_category': 'இந்த பிரிவில் இயக்குனர்கள் இல்லை',
      'add_director': 'இயக்குனரைச் சேர்க்கவும்',
      'edit_director': 'இயக்குனரைத் திருத்தவும்',
      'create_new_record': 'புதிய இயக்குனர் பதிவை உருவாக்கவும்',
      'update_info': 'இயக்குனர் தகவலைப் புதுப்பிக்கவும்',
      'identification': 'அடையாளம்',
      'full_name': 'முழு பெயர்',
      'enter_full_name': 'முழு பெயரை உள்ளிடவும்',
      'din_number': 'DIN எண்',
      'enter_din': '7-8 இலக்க DIN ஐ உள்ளிடவும்',
      'pan_number': 'PAN எண்',
      'aadhaar_number': 'ஆதார் எண்',
      'contact_info': 'தொடர்பு தகவல்',
      'email_id': 'மின்னஞ்சல் முகவரி',
      'bank_linked_phone': 'வங்கியுடன் இணைக்கப்பட்ட போன்',
      'aadhaar_pan_phone': 'ஆதார்/PAN போன்',
      'email_linked_phone': 'மின்னஞ்சலுடன் இணைக்கப்பட்ட போன்',
      'address_info': 'முகவரி தகவல்',
      'aadhaar_address': 'ஆதார் முகவரி',
      'residential_address': 'வீட்டு முகவரி',
      'idbi_bank_details': 'IDBI வங்கி விவரங்கள்',
      'account_details': 'கணக்கு விவரங்கள்',
      'emudhra_details': 'eMUDHRA கணக்கு விவரங்கள்',
      'status_label': 'நிலை',
      'create_director': 'இயக்குனரை உருவாக்கவும்',
      'update_director': 'இயக்குனரைப் புதுப்பிக்கவும்',
      'name_required': 'பெயர் தேவை',
      'director_created_synced': 'இயக்குனர் உருவாக்கப்பட்டு மேகக்கணியுடன் ஒத்திசைக்கப்பட்டது',
      'director_updated_synced': 'இயக்குனர் புதுப்பிக்கப்பட்டு மேகக்கணியுடன் ஒத்திசைக்கப்பட்டது',
      'inactive': 'செயலற்றது',
      'enter_phone': 'தொலைபேசி எண்ணை உள்ளிடவும்',
      'phone_number': 'தொலைபேசி எண்',
      'enter_address_aadhaar': 'ஆதாரில் உள்ளபடி முகவரியை உள்ளிடவும்',
      'enter_residential_address': 'தற்போதைய வீட்டு முகவரியை உள்ளிடவும்',
      'enter_account_details_idbi': 'கணக்கு எண், வாடிக்கையாளர் ஐடி போன்றவற்றை உள்ளிடவும்',
      'enter_account_details_emudhra': 'கணக்கு எண், வங்கி பெயர், IFSC, கிளையை உள்ளிடவும்',
      'removed_directors': 'நீக்கப்பட்ட இயக்குனர்கள்',
      'search_removed_directors': 'நீக்கப்பட்ட இயக்குனர்களைத் தேடுங்கள்...',
      'restore': 'மீட்டமை',
      'delete_forever': 'நிரந்தரமாக நீக்கு',
      'permanently_delete_title': 'நிரந்தரமாக நீக்கவா?',
      'permanently_delete_confirm': '"{name}" ஐ நிரந்தரமாக நீக்க விரும்புகிறீர்களா?',
      'undone_action_warning': 'இந்தச் செயலை மாற்ற முடியாது!',
      'restore_success': '{name} மீட்டமைக்கப்பட்டது',
      'delete_forever_success': '{name} நிரந்தரமாக நீக்கப்பட்டது',
      'no_removed_directors': 'நீக்கப்பட்ட இயக்குனர்கள் யாரும் இல்லை',
      'all_directors_active': 'அனைத்து இயக்குனர்களும் தற்போது செயலில் உள்ளனர்',
      'removed': 'நீக்கப்பட்டது',
      'analytics_overview': 'பகுப்பாய்வு கண்ணோட்டம்',
      'performance_monitoring': 'செயல்திறன் மற்றும் இணக்கக் கண்காணிப்பு',
      'directorship_distribution': 'இயக்குனர் விநியோகம்',
      'active_inactive_status': 'செயலில் மற்றும் செயலற்ற நிலை',
      'data_integrity': 'தரவு ஒருமைப்பாடு',
      'completeness_validation': 'முழுமை மற்றும் சரிபார்ப்பு நிலை',
      'profile_completion': 'சுயவிவரப் பூர்த்தி',
      'din_validation': 'DIN சரிபார்ப்பு',
      'kyc_status': 'KYC நிலை',
      'total_records': 'மொத்த பதிவுகள்',
      'issues': 'சிக்கல்கள்',
      'synced': 'ஒத்திசைக்கப்பட்டது',
      'quarterly_audit_report': 'காலாண்டு தணிக்கை அறிக்கை',
      'full_compliance_check': 'அனைத்து ஆணைகளுக்கும் முழு இணக்கச் சரிபார்ப்பு',
      'export_master_report': 'மாஸ்டர் அறிக்கையை ஏற்றுமதி செய்',
      'download_success_msg': 'மாஸ்டர் அறிக்கை PDF பாதுகாப்பான சேமிப்பகத்தில் பதிவிறக்கம் செய்யப்பட்டது.',
      'opening_audit_report': 'விரிவான தணிக்கை அறிக்கையைத் திறக்கிறது...',
      'export_directors': 'இயக்குனர்களை ஏற்றுமதி செய்',
      'directors_selected': '{total}-ல் {count} இயக்குனர்கள் தேர்ந்தெடுக்கப்பட்டனர்',
      'export_format': 'ஏற்றுமதி வடிவம்',
      'document_settings': 'ஆவண அமைப்புகள்',
      'report_title': 'அறிக்கை தலைப்பு',
      'enter_report_title': 'அறிக்கை தலைப்பை உள்ளிடவும்',
      'company_name_optional': 'நிறுவனத்தின் பெயர் (விருப்பமானது)',
      'enter_company_name': 'நிறுவனத்தின் பெயரை உள்ளிடவும்',
      'file_name': 'கோப்பு பெயர்',
      'enter_file_name': 'கோப்பு பெயரை உள்ளிடவும்',
      'include_header': 'தலைப்பைச் சேர்க்கவும்',
      'add_title_metadata': 'மேலே தலைப்பு மற்றும் மெட்டாடேட்டாவைச் சேர்க்கவும்',
      'include_timestamp': 'நேர முத்திரையைச் சேர்க்கவும்',
      'add_generation_date': 'உருவாக்கப்பட்ட தேதி மற்றும் நேரத்தைச் சேர்க்கவும்',
      'include_summary': 'சுருக்கத்தைச் சேர்க்கவும்',
      'add_stats_end': 'இறுதியில் புள்ளிவிவரங்களைச் சேர்க்கவும்',
      'privacy': 'தனியுரிமை',
      'aadhaar_privacy': 'ஆதார் தனியுரிமை',
      'unmasked': 'மறைக்கப்படவில்லை',
      'show_full_number': 'முழு எண்ணைக் காட்டு',
      'masked': 'மறைக்கப்பட்டது',
      'hide_digits': 'இலக்கங்களை மறை',
      'select_fields': 'புலங்களைத் தேர்ந்தெடுக்கவும்',
      'choose_fields_export': 'ஏற்றுமதியில் எந்தப் புலங்களைச் சேர்க்க வேண்டும் என்பதைத் தேர்ந்தெடுக்கவும்',
      'exporting': 'ஏற்றுமதி செய்கிறது...',
      'export_count_directors': '{count} இயக்குனர்களை ஏற்றுமதி செய்',
      'select_directors_to_export': 'ஏற்றுமதி செய்ய இயக்குனர்களைத் தேர்ந்தெடுக்கவும்',
      'all_directors_selected': 'அனைத்து இயக்குனர்களும் தேர்ந்தெடுக்கப்பட்டனர்',
      'tap_choose_specific': 'குறிப்பிட்ட இயக்குனர்களைத் தேர்வு செய்ய தட்டவும்',
      'search_directors': 'இயக்குனர்களைத் தேடுங்கள்...',
      'hide_selection': 'தேர்வை மறை',
      'selected': 'தேர்ந்தெடுக்கப்பட்டது',
      'name_case_format': 'பெயர் வகை வடிவமைப்பு',
      'choose_case_display': 'இயக்குனர் பெயர்கள் எவ்வாறு காட்டப்படுகின்றன என்பதைத் தேர்ந்தெடுக்கவும்',
      'title_case': 'தலைப்பு வகை',
      'uppercase': 'மேல் எழுத்து',
      'lowercase': 'கீழ் எழுத்து',
      'logout_confirm_msg': 'உங்கள் கணக்கிலிருந்து வெளியேற விரும்புகிறீர்களா?',
      'about_app_desc': 'கிளவுட் ஒத்திசைவு மற்றும் நிகழ்நேர ஒத்துழைப்புடன் கூடிய தொழில்முறை இயக்குனர் மேலாண்மை தீர்வு.',
      'close': 'மூடு',
      'default_language_desc': 'இயல்புநிலை மொழி',
      'live_synced': 'நேரடி • ஒத்திசைவு',
      'syncing': 'ஒத்திசைக்கிறது...',
      'synced_directors_msg': '{count} இயக்குனர்கள் ஒத்திசைக்கப்பட்டனர்',
      'no_directors_yet': 'இன்னும் இயக்குனர்கள் இல்லை',
      'start_adding_msg': 'முதல் இயக்குனரைச் சேர்ப்பதன் மூலம் தொடங்கவும்',
      'mismatch': 'பொருந்தவில்லை',
      's_no': 'வ.எண்',
      'pan': 'PAN',
      'aadhaar_address': 'ஆதார் முகவரி',
      'residential_address': 'இருப்பிட முகவரி',
      'idbi_account': 'IDBI கணக்கு',
      'emudhra_account': 'eMudhra கணக்கு',
      'bank_phone': 'வங்கியுடன் இணைக்கப்பட்ட தொலைபேசி',
      'aadhaar_phone': 'ஆதார்/PAN தொலைபேசி',
      'email_phone': 'மின்னஞ்சலுடன் இணைக்கப்பட்ட தொலைபேசி',
      'has_valid_din': 'செல்லுபடியாகும் DIN உள்ளதா',
      'generated_at': 'உருவாக்கப்பட்டது',
      'summary_section': 'சுருக்கம்',
      'yes': 'ஆம்',
      'no': 'இல்லை',

      // Login Screen - உள்நுழைவு திரை
      'welcome': 'வரவேற்கிறோம்',
      'login_title': 'இயக்குனர் மையம்',
      'secure_access_msg': 'உங்கள் இயக்குனர் பதிவுகளுக்கான பாதுகாப்பான அணுகல்',
      'username': 'பயனர் பெயர்',
      'password': 'கடவுச்சொல்',
      'enter_username': 'உங்கள் பயனர் பெயரை உள்ளிடவும்',
      'enter_password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
      'sign_in': 'உள்நுழைக',
      'demo_credentials': 'டெமோ: admin / password',
      'invalid_credentials': 'தவறான சான்றுகள். மீண்டும் முயற்சிக்கவும்.',
      'field_required': 'இந்த புலம் தேவை',

      // Dashboard - டாஷ்போர்டு
      'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
      'overview': 'கண்ணோட்டம்',
      'total_directors': 'மொத்த இயக்குனர்கள்',
      'active_directors': 'செயலில் உள்ள இயக்குனர்கள்',
      'pending_issues': 'நிலுவையில் உள்ள சிக்கல்கள்',
      'recent_activity': 'சமீபத்திய செயல்பாடு',
      'key_metrics': 'முக்கிய அளவீடுகள்',
      'quick_actions': 'விரைவு செயல்கள்',
      'recent_directors': 'சமீபத்திய இயக்குனர்கள்',
      'view_all': 'அனைத்தையும் காண்க',
      'no_din_proposal': 'DIN இல்லை / திட்டம்',
      'address_mismatch': 'முகவரி பொருந்தாது',
      'sync': 'ஒத்திசை',
      'mismatch': 'பொருந்தாது',
      'synced_directors': 'இயக்குனர்கள் ஒத்திசைக்கப்பட்டனர்',
      'live_synced': 'நேரடி • ஒத்திசைக்கப்பட்டது',
      'syncing': 'ஒத்திசைக்கிறது...',

      // Profile - சுயவிவரம்
      'admin_user': 'நிர்வாக பயனர்',
      'administrator': 'நிர்வாகி',
      'edit_profile': 'சுயவிவரத்தைத் திருத்து',

      // Misc - இதர
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'english': 'English',
      'tamil': 'தமிழ்',
      'home': 'முகப்பு',
      'cards': 'அட்டைகள்',
      'table': 'அட்டவணை',
      'cols': 'நெடுவரிசை',
      'add_to_category': '"{category}" இல் சேர்க்கவும்',
      'directors_available_count': '{count} இயக்குனர்கள் கிடைக்கின்றனர். சேர்க்க தட்டவும்.',
      'all_directors_assigned': 'அனைத்து இயக்குனர்களும் ஒதுக்கப்பட்டனர்!',
      'no_more_to_add': 'சேர்க்க வேறு இயக்குனர்கள் இல்லை.',
      'added_success': '{name} சேர்க்கப்பட்டார்',
      'search_hint_name_din': 'பெயர் அல்லது DIN மூலம் தேடுங்கள்...',
      'done': 'முடிந்தது',

      // Forms
      'dynamic_forms': 'DJM Form',
      'fill_manage_forms': 'DJM படிவங்களை நிரப்ப அல்லது நிர்வகிக்க',
      'create_form': 'DJM படிவத்தை உருவாக்கு',
      'edit_form': 'DJM படிவத்தைத் திருத்து',
      'delete_form': 'DJM படிவத்தை நீக்கு',
      'form_title': 'DJM படிவத் தலைப்பு',
      'form_description': 'DJM படிவ விளக்கம்',
      'add_field': 'புலத்தைச் சேர்',
      'save_form': 'DJM படிவத்தைச் சேமி',
      'view_reports': 'அறிக்கைகளைக் காண்க',
      'responses': 'பதில்கள்',
      'export_csv': 'Excel (CSV) ஏற்றுமதி',
      'export_pdf': 'PDF ஏற்றுமதி',
      'no_forms_available': 'இன்னும் DJM படிவங்கள் இல்லை',
      'submit_form': 'DJM படிவத்தைச் சமர்ப்பி',
      'form_submitted_success': 'DJM படிவம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
    },
  };
}

/// Global instance
final localizationService = LocalizationService();

/// Extension for easy access
extension LocalizationExtension on String {
  String get tr => localizationService.tr(this);
}
